export default {
  OPTION_INITIALIZED: 'OPTION_INITIALIZED', // 配置项初始化完成
  SDK_INITIALIZED: 'SDK_INITIALIZED', // SDK初始化完成
  SDK_INITIALIZED_COMPLATE: 'SDK_INITIALIZED_COMPLATE', // SDK初始化完成并发送首次visit和page后
  OPTION_CHANGE: 'OPTION_CHANGE', // 设置变更事件
  UID_UPDATE: 'UID_UPDATE', // uId变更事件
  USERID_UPDATE: 'USERID_UPDATE', // userId变更事件
  USERKEY_UPDATE: 'USERKEY_UPDATE', // userKey变更事件
  GIOID_UPDATE: 'GIOID_UPDATE', // gioId变更事件
  SESSIONID_UPDATE: 'SESSIONID_UPDATE', // sessionId变更事件
  SET_USERID: 'SET_USERID', // setUserId事件
  SET_USERKEY: 'SET_USERKEY' // setUserKey事件
};
